import type { Question, Subject, Topic } from '../src/models';
import type { SeedBundle } from './seedSecurityPlus';

const now = new Date().toISOString();

const subjectId = 'gex1015';

const topics: Topic[] = [
  { id: 'gex-goodness', subjectId, name: 'Week 2: Goodness (Hedonism, Desire Theory, Objective List Theory)' },
  { id: 'gex-right-wrong-1', subjectId, name: 'Week 3: Right & Wrong I (Consequentialism, Utilitarianism, Singer)' },
  { id: 'gex-right-wrong-2', subjectId, name: 'Week 4: Right & Wrong II (Non-Consequentialism, Kant, Trolley Problems, Thomson)' },
  { id: 'gex-logic-relativism', subjectId, name: 'Week 5: Logical Reasoning & Cultural Relativism' },
  { id: 'gex-religion', subjectId, name: 'Week 6: Religion & The Problem of Evil' },
];

const questions: Question[] = [
  // ═══════════════════════════════════════════════════════════════════════
  // WEEK 2: GOODNESS
  // ═══════════════════════════════════════════════════════════════════════

  // --- Instrumental vs Non-instrumental Value ---
  {
    id: 'gex-001',
    subjectId,
    topicIds: ['gex-goodness'],
    type: 'mcq_single',
    stem: 'Which of the following best describes something that is instrumentally good?',
    choices: [
      { id: 'a', text: 'It is good for its own sake or in and of itself' },
      { id: 'b', text: 'It is good because of the good things it brings about' },
      { id: 'c', text: 'It is always good, regardless of context' },
      { id: 'd', text: 'It is good only if you desire it' },
    ],
    correctChoiceIds: ['b'],
    explanation: 'Something is instrumentally good if it is good because it is a means for a further end — i.e., because of the good things it brings about. E.g., money and vaccinations are instrumentally good.',
    difficulty: 1,
    createdAt: now,
    updatedAt: now,
  },
  {
    id: 'gex-002',
    subjectId,
    topicIds: ['gex-goodness'],
    type: 'mcq_single',
    stem: 'Can something be both instrumentally and non-instrumentally good?',
    choices: [
      { id: 'a', text: 'No — something must be one or the other, never both' },
      { id: 'b', text: 'Yes — for example, pleasure you get from exercising is good for its own sake and also leads to further good things' },
      { id: 'c', text: 'Yes, but only according to the Desire Theory' },
      { id: 'd', text: 'No — only pleasure can be non-instrumentally good' },
    ],
    correctChoiceIds: ['b'],
    explanation: 'As noted in the lecture, something can be both instrumentally and non-instrumentally good. Pleasure from exercising is good in itself (non-instrumental) and also leads to health benefits (instrumental).',
    difficulty: 2,
    createdAt: now,
    updatedAt: now,
  },

  // --- Hedonism ---
  {
    id: 'gex-003',
    subjectId,
    topicIds: ['gex-goodness'],
    type: 'mcq_single',
    stem: 'According to hedonism, what is the ONLY thing that is non-instrumentally good?',
    choices: [
      { id: 'a', text: 'Desire satisfaction' },
      { id: 'b', text: 'Knowledge and friendship' },
      { id: 'c', text: 'Pleasure' },
      { id: 'd', text: 'Moral virtue' },
    ],
    correctChoiceIds: ['c'],
    explanation: 'Hedonism holds that pleasure is the ONLY thing that is non-instrumentally good, and pain is the ONLY thing that is non-instrumentally bad.',
    difficulty: 1,
    createdAt: now,
    updatedAt: now,
  },
  {
    id: 'gex-004',
    subjectId,
    topicIds: ['gex-goodness'],
    type: 'mcq_single',
    stem: 'What do hedonists mean by "pleasure"?',
    choices: [
      { id: 'a', text: 'Only physical/bodily sensations that feel good' },
      { id: 'b', text: 'Any state of mind that feels good, including bodily sensations, positive emotions, and "higher" pleasures like intellectual pleasure' },
      { id: 'c', text: 'Only "higher" pleasures such as art and intellect, not base physical pleasures' },
      { id: 'd', text: 'Happiness in the sense of long-term life satisfaction' },
    ],
    correctChoiceIds: ['b'],
    explanation: 'For hedonists, pleasure is any state of mind that feels good: pleasant bodily sensations, positive emotions (joy, pride), and "higher" pleasures (artistic, intellectual). It is not limited to physical pleasure.',
    difficulty: 2,
    createdAt: now,
    updatedAt: now,
  },
  {
    id: 'gex-005',
    subjectId,
    topicIds: ['gex-goodness'],
    type: 'mcq_multi',
    stem: 'Which of the following are listed in the lecture as attractions of hedonism? Select all that apply.',
    choices: [
      { id: 'a', text: 'It\'s hard to deny that pleasure is non-instrumentally good' },
      { id: 'b', text: 'It\'s hard to think of anything besides pleasure that\'s obviously non-instrumentally good' },
      { id: 'c', text: 'Hedonism can allow many different ways to live a good life because sources of pleasure vary widely among individuals' },
      { id: 'd', text: 'Hedonism is the simplest theory, and simpler theories are always more likely to be true' },
    ],
    correctChoiceIds: ['a', 'b', 'c'],
    explanation: 'The lecture lists three attractions of hedonism: (A) it\'s hard to deny pleasure is non-instrumentally good, (B) it\'s hard to think of other obviously non-instrumentally good things, and (C) it allows many ways to live a good life. D is not mentioned.',
    difficulty: 2,
    createdAt: now,
    updatedAt: now,
  },

  // --- Experience Machine (Nozick) ---
  {
    id: 'gex-006',
    subjectId,
    topicIds: ['gex-goodness'],
    type: 'mcq_single',
    stem: 'What is Nozick\'s main conclusion from the Experience Machine thought experiment?',
    choices: [
      { id: 'a', text: 'Pleasure is only instrumentally valuable' },
      { id: 'b', text: 'Pleasure is only non-instrumentally valuable' },
      { id: 'c', text: 'Pleasure is more valuable than other things' },
      { id: 'd', text: 'Pleasure is not the only thing that is instrumentally valuable' },
      { id: 'e', text: 'Pleasure is not the only thing that is non-instrumentally valuable' },
    ],
    correctChoiceIds: ['e'],
    explanation: 'Nozick\'s conclusion is that pleasure is not the only thing that is non-instrumentally valuable. Our reluctance to plug into the machine suggests we value things beyond mere pleasurable experiences — such as actually doing things, being a certain kind of person, and contact with reality.',
    difficulty: 2,
    createdAt: now,
    updatedAt: now,
  },
  {
    id: 'gex-007',
    subjectId,
    topicIds: ['gex-goodness'],
    type: 'mcq_multi',
    stem: 'According to Nozick, what are the reasons people would not plug into the experience machine? Select all that apply.',
    choices: [
      { id: 'a', text: 'We want to actually DO certain things, not just have the experience of doing them' },
      { id: 'b', text: 'We want to BE a certain kind of person (courageous, kind, etc.), not an indeterminate blob' },
      { id: 'c', text: 'We want contact with a deeper reality, not a man-made reality' },
      { id: 'd', text: 'We are afraid the machine will malfunction' },
    ],
    correctChoiceIds: ['a', 'b', 'c'],
    explanation: 'Nozick gives three reasons: (1) we want to DO things, not just experience doing them; (2) we want to BE a certain sort of person; (3) we want contact with deeper reality. The thought experiment stipulates the machine won\'t malfunction, so D is not a valid reason.',
    difficulty: 2,
    createdAt: now,
    updatedAt: now,
  },
  {
    id: 'gex-008',
    subjectId,
    topicIds: ['gex-goodness'],
    type: 'mcq_single',
    stem: 'Which of the following is true about the Experience Machine thought experiment?',
    choices: [
      { id: 'a', text: 'You can have genuine interactions with other people while in the machine' },
      { id: 'b', text: 'You will only experience pleasure in the machine — no pain at all' },
      { id: 'c', text: 'While in the machine, you won\'t know you\'re in it; you\'ll think everything is actually happening' },
      { id: 'd', text: 'You can exit the machine whenever you want' },
    ],
    correctChoiceIds: ['c'],
    explanation: 'While in the machine, you won\'t know you\'re there — you\'ll think it\'s all actually happening. You cannot have genuine interactions with others (A is false). You CAN choose to experience some pain for greater pleasure later (B is false). You come out only every two years to reprogram (D is misleading).',
    difficulty: 2,
    createdAt: now,
    updatedAt: now,
  },
  {
    id: 'gex-009',
    subjectId,
    topicIds: ['gex-goodness'],
    type: 'mcq_multi',
    stem: 'What could hedonists say in response to the Experience Machine objection? Select all that apply.',
    choices: [
      { id: 'a', text: 'People\'s intuitions about the machine are influenced by irrelevant factors like worry about malfunctions or moral guilt about leaving others behind' },
      { id: 'b', text: 'People may prefer continuing the status quo out of fear of the unfamiliar, not because they genuinely value non-experiential things' },
      { id: 'c', text: 'If people were already IN the machine, many might choose to remain rather than switch to a real life with less pleasure' },
      { id: 'd', text: 'Nozick\'s argument is invalid because it uses the wrong argument form' },
    ],
    correctChoiceIds: ['a', 'b', 'c'],
    explanation: 'The lecture mentions three possible hedonist responses: intuitions are influenced by irrelevant factors (worry, guilt), status quo bias / fear of unfamiliar, and the framing effect — if already in the machine, people might choose to stay. D is not a valid objection.',
    difficulty: 3,
    createdAt: now,
    updatedAt: now,
  },

  // --- Desire Theory ---
  {
    id: 'gex-010',
    subjectId,
    topicIds: ['gex-goodness'],
    type: 'mcq_single',
    stem: 'According to the Desire Theory, what is the only thing that is non-instrumentally good for a person?',
    choices: [
      { id: 'a', text: 'Pleasure' },
      { id: 'b', text: 'The fulfillment of that person\'s desires' },
      { id: 'c', text: 'Objective goods like knowledge and friendship' },
      { id: 'd', text: 'Moral virtue' },
    ],
    correctChoiceIds: ['b'],
    explanation: 'The Desire Theory holds that the fulfillment of your desires is the only thing non-instrumentally good for you, and the frustration of your desires is the only thing non-instrumentally bad for you.',
    difficulty: 1,
    createdAt: now,
    updatedAt: now,
  },
  {
    id: 'gex-011',
    subjectId,
    topicIds: ['gex-goodness'],
    type: 'mcq_single',
    stem: 'Is the following statement true or false?\n\nOn the Desire Theory, it is possible that a person doesn\'t know how valuable their life is.',
    choices: [
      { id: 'a', text: 'True' },
      { id: 'b', text: 'False' },
    ],
    correctChoiceIds: ['a'],
    explanation: 'True. A person may not know whether their desires are fulfilled — e.g., a mother who desires her missing child\'s safety doesn\'t know if the child is safe. On the Desire Theory, she therefore doesn\'t know how valuable her life is. (This was a question on the 2024 midterm.)',
    difficulty: 2,
    createdAt: now,
    updatedAt: now,
  },
  {
    id: 'gex-012',
    subjectId,
    topicIds: ['gex-goodness'],
    type: 'mcq_single',
    stem: 'How can the Desire Theory and Hedonism disagree?',
    choices: [
      { id: 'a', text: 'They can\'t — they always agree on what is good for a person' },
      { id: 'b', text: 'Some people might not desire pleasure, and desire fulfillment doesn\'t always produce pleasure (e.g., when you don\'t know your desire is fulfilled)' },
      { id: 'c', text: 'The Desire Theory says pain is never bad, while hedonism says pain is bad' },
      { id: 'd', text: 'Hedonism allows many ways to live a good life but the Desire Theory does not' },
    ],
    correctChoiceIds: ['b'],
    explanation: 'The Desire Theory and Hedonism can disagree because: (1) some people might not desire pleasure, and (2) you might not get pleasure from desire fulfillment (e.g., when you don\'t know your desire is fulfilled).',
    difficulty: 3,
    createdAt: now,
    updatedAt: now,
  },
  {
    id: 'gex-013',
    subjectId,
    topicIds: ['gex-goodness'],
    type: 'mcq_single',
    stem: 'Which of the following is an objection to the Desire Theory?',
    choices: [
      { id: 'a', text: 'It cannot explain why we should not plug into the experience machine' },
      { id: 'b', text: 'It doesn\'t allow for different ways to live a good life' },
      { id: 'c', text: 'In some cases (e.g., an oppressed slave wanting only to serve their master), desire fulfillment doesn\'t seem genuinely good for the person' },
      { id: 'd', text: 'It claims that only pleasure is non-instrumentally good' },
    ],
    correctChoiceIds: ['c'],
    explanation: 'The objection is that in some cases the person seems to desire the "wrong thing" (an oppressed slave wanting only to serve, an alcoholic just wanting to drink). Desire fulfillment in these cases doesn\'t seem genuinely good, but the Desire Theory can\'t easily explain this without admitting desire-independent goods.',
    difficulty: 3,
    createdAt: now,
    updatedAt: now,
  },

  // --- Objective List Theory ---
  {
    id: 'gex-014',
    subjectId,
    topicIds: ['gex-goodness'],
    type: 'mcq_multi',
    stem: 'Which of the following are attractions of Objective List Theories? Select all that apply.',
    choices: [
      { id: 'a', text: 'They can explain why we should not plug into the experience machine' },
      { id: 'b', text: 'They can explain why the fulfillment of some desires is not good for the person' },
      { id: 'c', text: 'They are never élitist because they respect individual autonomy' },
      { id: 'd', text: 'They have a clear explanation of what all items on the list have in common' },
    ],
    correctChoiceIds: ['a', 'b'],
    explanation: 'Objective List Theories can explain why we shouldn\'t plug into the experience machine (we\'d miss objective goods like knowledge, friendship, achievement) and why some desire fulfillments aren\'t genuinely good. However, they ARE criticized as élitist (C is false) and it IS difficult to explain what list items have in common (D is false).',
    difficulty: 3,
    createdAt: now,
    updatedAt: now,
  },

  // --- Three Philosophers / Experience Machine Application ---
  {
    id: 'gex-015',
    subjectId,
    topicIds: ['gex-goodness'],
    type: 'mcq_single',
    stem: 'Anna wants only pleasure and nothing else, and decides to spend her entire life in the experience machine. Philosopher A says Anna made the right decision and it\'s right for everyone. Philosopher B says Anna didn\'t make the right decision. Philosopher C agrees Anna made the right decision but says it isn\'t right for many others. What theory does Philosopher C most likely endorse?',
    choices: [
      { id: 'a', text: 'Hedonism' },
      { id: 'b', text: 'Objective List Theory' },
      { id: 'c', text: 'Desire Theory' },
      { id: 'd', text: 'Classic Utilitarianism' },
    ],
    correctChoiceIds: ['c'],
    explanation: 'Philosopher C is a desire theorist. Anna only desires pleasure → experience machine is right for her. But most others have desires that can\'t be fulfilled in the machine → not right for them. Philosopher A is a hedonist (right for everyone since machine = more pleasure). Philosopher B endorses Objective List Theory (objective goods matter regardless of desires).',
    difficulty: 3,
    createdAt: now,
    updatedAt: now,
  },
  {
    id: 'gex-016',
    subjectId,
    topicIds: ['gex-goodness'],
    type: 'mcq_single',
    stem: 'Assume life in the experience machine provides more net pleasure than life in reality for everyone. Philosopher A says plugging in is the right decision for everyone. Which theory does Philosopher A most likely endorse?',
    choices: [
      { id: 'a', text: 'Desire Theory' },
      { id: 'b', text: 'Hedonism' },
      { id: 'c', text: 'Objective List Theory' },
      { id: 'd', text: 'Cultural Relativism' },
    ],
    correctChoiceIds: ['b'],
    explanation: 'A hedonist would say the experience machine is right for everyone because it provides more net pleasure (the only non-instrumental good on hedonism) than reality for everyone.',
    difficulty: 2,
    createdAt: now,
    updatedAt: now,
  },

  // ═══════════════════════════════════════════════════════════════════════
  // WEEK 3: RIGHT AND WRONG I — CONSEQUENTIALISM, UTILITARIANISM, SINGER
  // ═══════════════════════════════════════════════════════════════════════

  // --- Moral Categories ---
  {
    id: 'gex-017',
    subjectId,
    topicIds: ['gex-right-wrong-1'],
    type: 'mcq_single',
    stem: 'Which of the following best describes a morally supererogatory action?',
    choices: [
      { id: 'a', text: 'An action that is morally wrong' },
      { id: 'b', text: 'An action that is morally required (obligatory)' },
      { id: 'c', text: 'An action that is morally good but not morally required — going above and beyond one\'s moral duties' },
      { id: 'd', text: 'An action that is morally neutral' },
    ],
    correctChoiceIds: ['c'],
    explanation: 'A supererogatory action is morally good but not morally required — it is "going above and beyond" one\'s moral duties. It is not wrong NOT to perform it. Example: jumping on a grenade to save others.',
    difficulty: 1,
    createdAt: now,
    updatedAt: now,
  },
  {
    id: 'gex-018',
    subjectId,
    topicIds: ['gex-right-wrong-1'],
    type: 'mcq_single',
    stem: 'According to how philosophers usually use the terms, what is the relationship between morally required actions and morally permissible (right) actions?',
    choices: [
      { id: 'a', text: 'They are the same set of actions' },
      { id: 'b', text: 'Required actions are a subset of permissible actions' },
      { id: 'c', text: 'Permissible actions are a subset of required actions' },
      { id: 'd', text: 'They are completely separate categories' },
    ],
    correctChoiceIds: ['b'],
    explanation: 'Morally required (obligatory) actions are a subset of morally permissible (right) actions. All required actions are permissible, but not all permissible actions are required — some are merely neutral or supererogatory. This was tested in the 2024 midterm (Q14).',
    difficulty: 2,
    createdAt: now,
    updatedAt: now,
  },

  // --- Classic Utilitarianism ---
  {
    id: 'gex-019',
    subjectId,
    topicIds: ['gex-right-wrong-1'],
    type: 'mcq_single',
    stem: 'According to classic utilitarianism, a right action is one that:',
    choices: [
      { id: 'a', text: 'Produces more pleasure than pain' },
      { id: 'b', text: 'Maximizes total net pleasure among all available actions' },
      { id: 'c', text: 'Follows the moral code of one\'s society' },
      { id: 'd', text: 'Treats people as ends in themselves, never merely as means' },
    ],
    correctChoiceIds: ['b'],
    explanation: 'Classic utilitarianism says a right action MAXIMIZES total net pleasure (total pleasure minus total pain) among the available actions. Simply producing more pleasure than pain (A) is not sufficient — it must produce the MOST net pleasure of all available options.',
    difficulty: 2,
    createdAt: now,
    updatedAt: now,
  },
  {
    id: 'gex-020',
    subjectId,
    topicIds: ['gex-right-wrong-1'],
    type: 'mcq_single',
    stem: 'Why is the slogan "the greatest happiness for the greatest number" not entirely accurate in describing classic utilitarianism?',
    choices: [
      { id: 'a', text: 'Because classic utilitarianism only cares about the happiness of the majority' },
      { id: 'b', text: 'Because not just pleasure but also pain matters, and an action benefiting the greatest number may not always be the right action' },
      { id: 'c', text: 'Because classic utilitarianism focuses on rules, not individual actions' },
      { id: 'd', text: 'Because classic utilitarianism is a form of non-consequentialism' },
    ],
    correctChoiceIds: ['b'],
    explanation: 'The slogan is inaccurate for two reasons: (1) not just pleasure but also pain matters in determining right/wrong; (2) an action that benefits the greatest number of people may not always be the right action — what matters is TOTAL net pleasure, not the number of people benefited. (From 2024 midterm Q11.)',
    difficulty: 3,
    createdAt: now,
    updatedAt: now,
  },
  {
    id: 'gex-021',
    subjectId,
    topicIds: ['gex-right-wrong-1'],
    type: 'mcq_single',
    stem: 'There are 10 people affected by your action.\n\nAction 1: each person experiences 1 unit of pleasure (no pain) = 10 units total.\nAction 2: one person experiences 50 units of pleasure; the other 9 experience 1 unit of pain each = 50 - 9 = 41 units total.\n\nWhich action is right according to classic utilitarianism?',
    choices: [
      { id: 'a', text: 'Action 1, because it benefits the greatest number of people' },
      { id: 'b', text: 'Action 2, because it maximizes total net pleasure' },
      { id: 'c', text: 'Both are right because both produce net pleasure' },
      { id: 'd', text: 'Neither is right because one of them causes pain' },
    ],
    correctChoiceIds: ['b'],
    explanation: 'Action 2 produces 41 units of net pleasure vs. Action 1\'s 10 units. Classic utilitarianism says the right action maximizes total net pleasure — so Action 2 is right, even though it benefits fewer people. This shows why "greatest happiness for greatest number" is misleading.',
    difficulty: 2,
    createdAt: now,
    updatedAt: now,
  },
  {
    id: 'gex-022',
    subjectId,
    topicIds: ['gex-right-wrong-1'],
    type: 'mcq_single',
    stem: 'Suppose an action generates 10 units of pleasure and 10 units of pain in total. What is the moral status of this action according to classic utilitarianism?',
    choices: [
      { id: 'a', text: 'Morally permissible' },
      { id: 'b', text: 'Morally wrong, since net pleasure is zero' },
      { id: 'c', text: 'Morally neutral' },
      { id: 'd', text: 'We need more information — we don\'t know what other available actions produce' },
    ],
    correctChoiceIds: ['d'],
    explanation: 'We need more information. Classic utilitarianism requires comparing this action to ALL other available actions. If all alternatives produce less than 0 net pleasure, this action is right. If any alternative produces more, this action is wrong. (From 2024 midterm Q13.)',
    difficulty: 3,
    createdAt: now,
    updatedAt: now,
  },
  {
    id: 'gex-023',
    subjectId,
    topicIds: ['gex-right-wrong-1'],
    type: 'mcq_single',
    stem: 'Action A will generate 2 units of pleasure (and no pain) for a cat.\nAction B will generate 1 unit of pleasure (and no pain) for a human being.\nAssume a unit of pleasure is of the same amount and quality regardless of species.\n\nWhich action is right according to classic utilitarianism?',
    choices: [
      { id: 'a', text: 'Action A — the cat\'s pleasure is higher so it maximizes net pleasure' },
      { id: 'b', text: 'Action B — human pleasure always counts more' },
      { id: 'c', text: 'Both are right' },
      { id: 'd', text: 'Both are wrong' },
    ],
    correctChoiceIds: ['a'],
    explanation: 'Classic utilitarianism is impartial — anyone\'s pleasure matters equally if it is of the same amount and quality. Since a unit is the same regardless of species, Action A (2 units) maximizes net pleasure over Action B (1 unit). (From 2024 midterm Q12.)',
    difficulty: 2,
    createdAt: now,
    updatedAt: now,
  },

  // --- Key features of classic utilitarianism ---
  {
    id: 'gex-024',
    subjectId,
    topicIds: ['gex-right-wrong-1'],
    type: 'mcq_multi',
    stem: 'Which of the following are features of classic utilitarianism? Select all that apply.',
    choices: [
      { id: 'a', text: 'Impartial — anyone\'s pleasure matters equally if of same amount and quality' },
      { id: 'b', text: 'Demanding — only the action that maximizes net pleasure is right; all others are wrong' },
      { id: 'c', text: 'Context-sensitive — no type of action is always right or wrong' },
      { id: 'd', text: 'Deontological — some types of actions are always wrong regardless of consequences' },
    ],
    correctChoiceIds: ['a', 'b', 'c'],
    explanation: 'Classic utilitarianism is (A) impartial, (B) demanding, and (C) context-sensitive. It is NOT deontological — that\'s the opposite. On utilitarianism, even torture could be right if it maximizes total net pleasure in a given context.',
    difficulty: 2,
    createdAt: now,
    updatedAt: now,
  },
  {
    id: 'gex-025',
    subjectId,
    topicIds: ['gex-right-wrong-1'],
    type: 'mcq_single',
    stem: 'On classic utilitarianism, the set of morally right (permissible) actions is approximately equal to:',
    choices: [
      { id: 'a', text: 'The set of supererogatory actions' },
      { id: 'b', text: 'The set of morally required (obligatory) actions' },
      { id: 'c', text: 'The set of morally neutral actions' },
      { id: 'd', text: 'The union of required, neutral, and supererogatory actions' },
    ],
    correctChoiceIds: ['b'],
    explanation: 'On classic utilitarianism, the set of morally right (permissible) actions is approximately equal to the set of morally required actions. Only the action maximizing net pleasure is right, and it is required. There is (almost) no room for supererogatory or merely neutral actions.',
    difficulty: 3,
    createdAt: now,
    updatedAt: now,
  },

  // --- Singer ---
  {
    id: 'gex-026',
    subjectId,
    topicIds: ['gex-right-wrong-1'],
    type: 'mcq_single',
    stem: 'What is Peter Singer\'s main conclusion in "Famine, Affluence, and Morality"?',
    choices: [
      { id: 'a', text: 'We should donate money to charity only if we feel like it' },
      { id: 'b', text: 'Donating to help people in developing countries is supererogatory — good but not required' },
      { id: 'c', text: 'We ought to donate a significant amount of money to help people suffering from extreme poverty, and it is morally WRONG not to do so' },
      { id: 'd', text: 'Only utilitarians should feel obligated to donate' },
    ],
    correctChoiceIds: ['c'],
    explanation: 'Singer argues that donating to help people in developing countries is not supererogatory but morally obligatory. It is morally WRONG not to donate (without sacrificing something of comparable moral importance).',
    difficulty: 1,
    createdAt: now,
    updatedAt: now,
  },
  {
    id: 'gex-027',
    subjectId,
    topicIds: ['gex-right-wrong-1'],
    type: 'mcq_single',
    stem: 'Singer\'s simplified argument:\n\nP1: We ought to save the drowning child.\nP2: If we ought to save the drowning child, then we ought to help people dying from extreme poverty.\nC: We ought to help people dying from extreme poverty.\n\nA philosopher responds: "Whether a person is physically near to us makes a difference in whether we ought to help them."\n\nWhich premise is this philosopher denying?',
    choices: [
      { id: 'a', text: 'Premise 1' },
      { id: 'b', text: 'Premise 2' },
      { id: 'c', text: 'Both premises' },
      { id: 'd', text: 'Neither — they are claiming the argument is invalid' },
    ],
    correctChoiceIds: ['b'],
    explanation: 'The philosopher is denying Premise 2. They accept that we ought to save the drowning child (P1), but claim that physical distance IS morally relevant — so the obligation to help someone nearby doesn\'t transfer to someone far away. This makes the argument unsound (not invalid). (From 2024 midterm Q10.)',
    difficulty: 3,
    createdAt: now,
    updatedAt: now,
  },
  {
    id: 'gex-028',
    subjectId,
    topicIds: ['gex-right-wrong-1'],
    type: 'mcq_single',
    stem: 'Is the following true or false?\n\nSinger\'s argument in "Famine, Affluence, and Morality" relies on utilitarianism.',
    choices: [
      { id: 'a', text: 'True' },
      { id: 'b', text: 'False' },
    ],
    correctChoiceIds: ['b'],
    explanation: 'False. Although Singer is a utilitarian, he explicitly states that his argument does NOT rely on utilitarianism. The argument is designed to be convincing to non-utilitarians as well.',
    difficulty: 2,
    createdAt: now,
    updatedAt: now,
  },
  {
    id: 'gex-029',
    subjectId,
    topicIds: ['gex-right-wrong-1'],
    type: 'mcq_single',
    stem: 'Singer addresses the objection that physical distance matters. What is his response?',
    choices: [
      { id: 'a', text: 'Physical distance does have moral significance, but we should help anyway' },
      { id: 'b', text: 'Physical distance is only psychologically relevant (affects what we likely will do) but not morally relevant; plus we can now effectively help people far away' },
      { id: 'c', text: 'Physical distance is irrelevant because we don\'t actually know how far developing countries are' },
      { id: 'd', text: 'Singer concedes that this is a valid objection to his argument' },
    ],
    correctChoiceIds: ['b'],
    explanation: 'Singer argues that physical proximity is psychologically relevant (we\'re more likely to help someone near us) but NOT morally relevant. We can\'t discriminate based on distance. Moreover, modern communication and transportation allow us to help effectively far away.',
    difficulty: 2,
    createdAt: now,
    updatedAt: now,
  },
  {
    id: 'gex-030',
    subjectId,
    topicIds: ['gex-right-wrong-1'],
    type: 'mcq_single',
    stem: 'Moonyoung owns more than enough shoes but buys a cheaper pair for $50 and donates $50 to charity, instead of buying a $100 pair. What would Singer say about this action?',
    choices: [
      { id: 'a', text: 'It is morally required because she is helping others' },
      { id: 'b', text: 'It is supererogatory — praiseworthy but not required' },
      { id: 'c', text: 'It is morally wrong because she should donate more' },
      { id: 'd', text: 'It is morally neutral' },
    ],
    correctChoiceIds: ['c'],
    explanation: 'Singer would say spending $50 on shoes she doesn\'t need is morally wrong. She could prevent more suffering by donating the full $100 (or at least more) without sacrificing anything of comparable moral importance. Even the moderate version of Singer\'s principle is very demanding. (From 2024 midterm Q9.)',
    difficulty: 3,
    createdAt: now,
    updatedAt: now,
  },
  {
    id: 'gex-031',
    subjectId,
    topicIds: ['gex-right-wrong-1'],
    type: 'mcq_single',
    stem: 'Singer addresses the objection: "I\'m the only one who can save the drowning child, but there are lots of other people in developed countries who could donate." What is his response?',
    choices: [
      { id: 'a', text: 'He agrees this makes a morally relevant difference' },
      { id: 'b', text: 'The existence of others who could also help does not reduce our moral obligation — you wouldn\'t be less obligated to save the drowning child just because others are also nearby and doing nothing' },
      { id: 'c', text: 'He says we should only donate if no one else is donating' },
      { id: 'd', text: 'He says collective action is the only morally acceptable approach' },
    ],
    correctChoiceIds: ['b'],
    explanation: 'Singer argues that the number of others in similar situations makes a psychological difference (one feels less guilty) but no real moral difference. You wouldn\'t be less obligated to save the drowning child just because other bystanders are also doing nothing.',
    difficulty: 2,
    createdAt: now,
    updatedAt: now,
  },

  // ═══════════════════════════════════════════════════════════════════════
  // WEEK 4: RIGHT AND WRONG II — NON-CONSEQUENTIALISM, KANT, TROLLEY, THOMSON
  // ═══════════════════════════════════════════════════════════════════════

  // --- Trolley Problems ---
  {
    id: 'gex-032',
    subjectId,
    topicIds: ['gex-right-wrong-2'],
    type: 'mcq_single',
    stem: 'What are the commonly held intuitions about the three trolley cases (Driver, Bystander, Bridge)?',
    choices: [
      { id: 'a', text: 'Option 2 (divert/kill one) is permissible in all three cases' },
      { id: 'b', text: 'Option 2 is impermissible in all three cases' },
      { id: 'c', text: 'Option 2 is permissible in Driver and Bystander but impermissible in Bridge' },
      { id: 'd', text: 'Option 2 is permissible only in Driver, impermissible in Bystander and Bridge' },
    ],
    correctChoiceIds: ['c'],
    explanation: 'The common intuitions (as taken by philosophers) are that Option 2 (saving five by sacrificing one) is permissible in Driver and Bystander, but impermissible in Bridge (pushing someone off a bridge).',
    difficulty: 1,
    createdAt: now,
    updatedAt: now,
  },
  {
    id: 'gex-033',
    subjectId,
    topicIds: ['gex-right-wrong-2'],
    type: 'mcq_single',
    stem: 'What would classic utilitarians say about the trolley cases (Driver, Bystander, Bridge), assuming no indirect consequences?',
    choices: [
      { id: 'a', text: 'Option 2 is permissible in all three — just think about the consequences (1 death vs. 5)' },
      { id: 'b', text: 'Option 2 is impermissible in Bridge because pushing is worse than diverting' },
      { id: 'c', text: 'Option 2 is impermissible in all three because killing is always wrong' },
      { id: 'd', text: 'It depends on the individual context' },
    ],
    correctChoiceIds: ['a'],
    explanation: 'Classic utilitarians think Option 2 is permissible (in fact, required) in ALL three cases because 1 death produces more total net pleasure than 5 deaths. The method of bringing about the death (diverting vs. pushing) is irrelevant — only consequences matter.',
    difficulty: 2,
    createdAt: now,
    updatedAt: now,
  },

  // --- Kant ---
  {
    id: 'gex-034',
    subjectId,
    topicIds: ['gex-right-wrong-2'],
    type: 'mcq_single',
    stem: 'According to Kant (as discussed in the lecture), it is morally wrong to:',
    choices: [
      { id: 'a', text: 'Treat persons as a means' },
      { id: 'b', text: 'Treat persons MERELY as a means' },
      { id: 'c', text: 'Ever cause harm to another person' },
      { id: 'd', text: 'Act based on consequences rather than duty' },
    ],
    correctChoiceIds: ['b'],
    explanation: 'Kant says it is morally wrong to treat persons MERELY as a means. Treating someone as a means is not always wrong — what matters is treating them merely as a means (where consent is a relevant factor in distinguishing the two).',
    difficulty: 2,
    createdAt: now,
    updatedAt: now,
  },
  {
    id: 'gex-035',
    subjectId,
    topicIds: ['gex-right-wrong-2'],
    type: 'mcq_single',
    stem: 'In the trolley cases, when are you treating the one person as a means (on the interpretation discussed in class)?',
    choices: [
      { id: 'a', text: 'In all three cases (Driver, Bystander, Bridge)' },
      { id: 'b', text: 'Only in Bridge' },
      { id: 'c', text: 'In both Bystander and Bridge' },
      { id: 'd', text: 'In none of the three cases' },
    ],
    correctChoiceIds: ['b'],
    explanation: 'In Driver and Bystander, you\'re not even treating the person as a means — the person\'s involvement is NOT part of the route by which your plan succeeds (if the person disappeared, you could still save the five). In Bridge, you ARE treating the person as a means (and probably merely as a means) because you need their body to stop the trolley.',
    difficulty: 3,
    createdAt: now,
    updatedAt: now,
  },
  {
    id: 'gex-036',
    subjectId,
    topicIds: ['gex-right-wrong-2'],
    type: 'mcq_single',
    stem: 'What is the "test" for whether you are treating someone as a means in the trolley cases?',
    choices: [
      { id: 'a', text: 'Whether the person consented to being used' },
      { id: 'b', text: 'Whether you intended to harm them' },
      { id: 'c', text: 'Roughly: whether you can still achieve your goal if the person disappears right before you perform the action' },
      { id: 'd', text: 'Whether the action produces more good than harm' },
    ],
    correctChoiceIds: ['c'],
    explanation: 'The lecture explains that roughly, a person\'s involvement is part of the route by which your plan succeeds (i.e., you\'re using them as a means) if you can\'t achieve your goal if the person disappears right before you act. In Bridge, if the large person disappears, you can\'t stop the trolley. In Bystander, if the one person disappears, the five are still saved.',
    difficulty: 3,
    createdAt: now,
    updatedAt: now,
  },

  // --- Loop Case ---
  {
    id: 'gex-037',
    subjectId,
    topicIds: ['gex-right-wrong-2'],
    type: 'mcq_multi',
    stem: 'Which of the following are true about the Loop case? Select all that apply.',
    choices: [
      { id: 'a', text: 'By throwing the switch, you are treating the one person as a means (and probably merely as a means)' },
      { id: 'b', text: 'The Loop case is a challenge for the Kantian approach because many people think it\'s permissible to throw the switch, yet you\'re treating the person as a means' },
      { id: 'c', text: 'Classic utilitarians would say it is morally wrong to throw the switch in Loop' },
      { id: 'd', text: 'Thomson would probably say it is morally wrong to throw the switch in Loop' },
    ],
    correctChoiceIds: ['a', 'b', 'd'],
    explanation: 'A: True — if the person disappears, the trolley loops back and kills the five, so you need the person. B: True — this challenges Kant\'s approach. C: False — utilitarians would say it\'s permissible (1 death vs. 5). D: True — Thomson argues that even throwing the switch in Bystander is wrong, so Loop (where you also use the person as a means) would be wrong too. (From 2024 midterm Q8.)',
    difficulty: 4,
    createdAt: now,
    updatedAt: now,
  },

  // --- Foot: Killing vs Letting Die ---
  {
    id: 'gex-038',
    subjectId,
    topicIds: ['gex-right-wrong-2'],
    type: 'mcq_single',
    stem: 'Philippa Foot proposed which principle to explain the common intuitions about trolley cases?',
    choices: [
      { id: 'a', text: 'It is always wrong to kill someone' },
      { id: 'b', text: 'Killing is morally worse than letting die' },
      { id: 'c', text: 'Intentions matter more than consequences' },
      { id: 'd', text: 'You should always choose the action that affects fewer people' },
    ],
    correctChoiceIds: ['b'],
    explanation: 'Foot proposed that killing is morally worse than letting die. This explains Driver (killing 5 vs. killing 1 → kill fewer) and Bridge (letting 5 die vs. killing 1 → letting die is less bad than killing).',
    difficulty: 2,
    createdAt: now,
    updatedAt: now,
  },
  {
    id: 'gex-039',
    subjectId,
    topicIds: ['gex-right-wrong-2'],
    type: 'mcq_single',
    stem: 'Why is the Bystander case a challenge for Foot\'s "killing vs. letting die" distinction?',
    choices: [
      { id: 'a', text: 'Because in Bystander, Option 2 is killing the one person but the common intuition says it\'s permissible — just like in Bridge where it\'s considered impermissible' },
      { id: 'b', text: 'Because in Bystander, both options involve letting people die' },
      { id: 'c', text: 'Because Foot\'s distinction doesn\'t apply to any trolley case' },
      { id: 'd', text: 'Because the distinction only works if there are more than 5 people' },
    ],
    correctChoiceIds: ['a'],
    explanation: 'In Bystander, Option 1 is letting five die and Option 2 is killing one — the same structure as Bridge. But the common intuition says Option 2 is permissible in Bystander and impermissible in Bridge. Foot\'s killing vs. letting die distinction can\'t explain this difference.',
    difficulty: 3,
    createdAt: now,
    updatedAt: now,
  },

  // --- Thomson ---
  {
    id: 'gex-040',
    subjectId,
    topicIds: ['gex-right-wrong-2'],
    type: 'mcq_single',
    stem: 'What does Thomson argue about the Bystander case in "Turning the Trolley" (2008)?',
    choices: [
      { id: 'a', text: 'It is morally permissible for the bystander to throw the switch' },
      { id: 'b', text: 'It is morally wrong for the bystander to throw the switch' },
      { id: 'c', text: 'The bystander is morally required to throw the switch' },
      { id: 'd', text: 'Thomson has no view on Bystander' },
    ],
    correctChoiceIds: ['b'],
    explanation: 'Thomson argues in "Turning the Trolley" that it is morally WRONG for the bystander to throw the switch. This goes against the common intuition. She uses the "Bystander\'s Three Options" thought experiment to support this.',
    difficulty: 2,
    createdAt: now,
    updatedAt: now,
  },
  {
    id: 'gex-041',
    subjectId,
    topicIds: ['gex-right-wrong-2'],
    type: 'mcq_single',
    stem: 'Thomson uses "Bystander\'s Three Options" where the bystander can: (i) do nothing (5 die), (ii) divert onto the one workman (1 dies), or (iii) divert onto himself (bystander dies). What does Thomson argue?',
    choices: [
      { id: 'a', text: 'The bystander must choose option (iii) to save the five' },
      { id: 'b', text: 'If the bystander can turn the trolley onto himself but instead turns it onto the workman, that is unacceptable — like stealing money to donate to charity instead of using your own' },
      { id: 'c', text: 'All three options are equally morally permissible' },
      { id: 'd', text: 'The bystander should always choose the option that saves the most lives' },
    ],
    correctChoiceIds: ['b'],
    explanation: 'Thomson argues that choosing (ii) — diverting onto the workman — is unacceptable when you could divert onto yourself. It\'s like stealing to donate to charity instead of using your own money. However, morality doesn\'t REQUIRE the bystander to choose (iii) — so (i) is permissible.',
    difficulty: 3,
    createdAt: now,
    updatedAt: now,
  },
  {
    id: 'gex-042',
    subjectId,
    topicIds: ['gex-right-wrong-2'],
    type: 'mcq_multi',
    stem: 'Which of the following are true about Bystander and Bridge? Select all that apply.',
    choices: [
      { id: 'a', text: 'Classic utilitarians think there is no morally relevant difference between Bystander and Bridge' },
      { id: 'b', text: 'According to Thomson, Option 2 is killing in both Bystander and Bridge' },
      { id: 'c', text: 'Foot\'s distinction between killing and letting die can easily explain the common intuition about Bystander vs. Bridge' },
      { id: 'd', text: 'Both classic utilitarians and Thomson think the common intuition is wrong (but for different reasons)' },
    ],
    correctChoiceIds: ['a', 'b', 'd'],
    explanation: 'A: True — for utilitarians, only consequences matter (1 vs. 5 deaths in both). B: True — Option 2 is killing in both cases. C: False — Foot\'s distinction CANNOT easily explain the asymmetry. D: True — utilitarians think Option 2 is permissible in both; Thomson thinks it\'s impermissible in both. (From 2024 midterm Q7.)',
    difficulty: 4,
    createdAt: now,
    updatedAt: now,
  },
  {
    id: 'gex-043',
    subjectId,
    topicIds: ['gex-right-wrong-2'],
    type: 'mcq_single',
    stem: 'Is the following true or false? Assume Thomson is right about what counts as killing.\n\n"If you don\'t need another person to achieve your aim (you can still achieve it if they disappear), then you\'re not killing the person."',
    choices: [
      { id: 'a', text: 'True' },
      { id: 'b', text: 'False' },
    ],
    correctChoiceIds: ['b'],
    explanation: 'False. Consider Bystander: you don\'t need the person on the sidetrack to save the five (if they disappear, the five are still saved). But by throwing the switch, you ARE still killing that person, according to Thomson. Not needing someone for your aim doesn\'t mean you\'re not killing them. (From 2024 midterm Q6.)',
    difficulty: 3,
    createdAt: now,
    updatedAt: now,
  },
  {
    id: 'gex-044',
    subjectId,
    topicIds: ['gex-right-wrong-2'],
    type: 'mcq_single',
    stem: 'According to Kant\'s theory (as interpreted in the lecture), does Option 2 amount to treating a person merely as a means in Bystander?',
    choices: [
      { id: 'a', text: 'Yes — you are using the person to save the five' },
      { id: 'b', text: 'No — you\'re not even treating the person as a means because you can still save the five if the person disappears' },
      { id: 'c', text: 'Yes — any action that causes death treats someone merely as a means' },
      { id: 'd', text: 'It depends on whether the person consented' },
    ],
    correctChoiceIds: ['b'],
    explanation: 'In Bystander, Option 2 doesn\'t even treat the person as a means (let alone merely as a means). If the person on the sidetrack disappeared, you could still save the five. So the person\'s involvement is not part of the route by which your plan succeeds. (From 2024 midterm Q7.)',
    difficulty: 3,
    createdAt: now,
    updatedAt: now,
  },

  // ═══════════════════════════════════════════════════════════════════════
  // WEEK 5: LOGICAL REASONING & CULTURAL RELATIVISM
  // ═══════════════════════════════════════════════════════════════════════

  // --- Arguments: Validity and Soundness ---
  {
    id: 'gex-045',
    subjectId,
    topicIds: ['gex-logic-relativism'],
    type: 'mcq_single',
    stem: 'A deductive argument is VALID if:',
    choices: [
      { id: 'a', text: 'Its premises are all true' },
      { id: 'b', text: 'Its conclusion is true' },
      { id: 'c', text: 'If the premises are all true, the conclusion MUST be true as well' },
      { id: 'd', text: 'It has at least two premises' },
    ],
    correctChoiceIds: ['c'],
    explanation: 'A valid argument is one where IF the premises are all true, the conclusion MUST be true. The truth of the conclusion follows necessarily from the truth of the premises. Whether the premises are actually true doesn\'t matter for validity.',
    difficulty: 1,
    createdAt: now,
    updatedAt: now,
  },
  {
    id: 'gex-046',
    subjectId,
    topicIds: ['gex-logic-relativism'],
    type: 'mcq_single',
    stem: 'A deductive argument is SOUND if:',
    choices: [
      { id: 'a', text: 'It is valid' },
      { id: 'b', text: 'Its premises are all true' },
      { id: 'c', text: 'It is valid AND its premises are all true' },
      { id: 'd', text: 'Its conclusion is true' },
    ],
    correctChoiceIds: ['c'],
    explanation: 'Soundness requires BOTH conditions: (1) the argument is valid, AND (2) all premises are actually true. If either condition fails, the argument is unsound.',
    difficulty: 1,
    createdAt: now,
    updatedAt: now,
  },
  {
    id: 'gex-047',
    subjectId,
    topicIds: ['gex-logic-relativism'],
    type: 'mcq_single',
    stem: 'Is the following true or false?\n\nAn argument with all false premises and a false conclusion can still be valid.',
    choices: [
      { id: 'a', text: 'True' },
      { id: 'b', text: 'False' },
    ],
    correctChoiceIds: ['a'],
    explanation: 'True. Validity only requires that IF the premises were true, the conclusion WOULD have to be true. It doesn\'t matter whether the premises or conclusion are actually true. Example: "If Taylor Swift is a philosopher, she is mortal. Taylor Swift is a philosopher. Therefore, she is mortal." — valid even though P2 is false. (From 2024 midterm Q2.)',
    difficulty: 2,
    createdAt: now,
    updatedAt: now,
  },
  {
    id: 'gex-048',
    subjectId,
    topicIds: ['gex-logic-relativism'],
    type: 'mcq_single',
    stem: 'Is the following true or false?\n\nIf an argument\'s premises and conclusion are all true, the argument is sound.',
    choices: [
      { id: 'a', text: 'True' },
      { id: 'b', text: 'False' },
    ],
    correctChoiceIds: ['b'],
    explanation: 'False. Soundness requires validity AND true premises. An argument can have all true premises and a true conclusion but still be invalid (and therefore unsound). Example: "All philosophers are men. Jungkook is not a philosopher. Therefore, Jungkook is not a man." — all premises and conclusion could be true, but the argument form is invalid. (From 2024 midterm Q3.)',
    difficulty: 3,
    createdAt: now,
    updatedAt: now,
  },

  // --- Four Argument Forms ---
  {
    id: 'gex-049',
    subjectId,
    topicIds: ['gex-logic-relativism'],
    type: 'mcq_single',
    stem: 'Which of the four common argument forms is this?\n\nP1. If A, then B.\nP2. A.\nC. Therefore, B.',
    choices: [
      { id: 'a', text: 'Always valid (Modus Ponens)' },
      { id: 'b', text: 'Always valid (Modus Tollens)' },
      { id: 'c', text: 'Always invalid (Denying the Antecedent)' },
      { id: 'd', text: 'Always invalid (Affirming the Consequent)' },
    ],
    correctChoiceIds: ['a'],
    explanation: 'This is Modus Ponens (affirming the antecedent) — always valid form (1). If A then B; A; therefore B.',
    difficulty: 1,
    createdAt: now,
    updatedAt: now,
  },
  {
    id: 'gex-050',
    subjectId,
    topicIds: ['gex-logic-relativism'],
    type: 'mcq_single',
    stem: 'Which of the four common argument forms is this?\n\nP1. If A, then B.\nP2. Not B.\nC. Therefore, Not A.',
    choices: [
      { id: 'a', text: 'Always valid (Modus Ponens)' },
      { id: 'b', text: 'Always valid (Modus Tollens)' },
      { id: 'c', text: 'Always invalid (Denying the Antecedent)' },
      { id: 'd', text: 'Always invalid (Affirming the Consequent)' },
    ],
    correctChoiceIds: ['b'],
    explanation: 'This is Modus Tollens (denying the consequent) — always valid form (2). If A then B; not B; therefore not A.',
    difficulty: 1,
    createdAt: now,
    updatedAt: now,
  },
  {
    id: 'gex-051',
    subjectId,
    topicIds: ['gex-logic-relativism'],
    type: 'mcq_single',
    stem: 'Which of the four common argument forms is this?\n\nP1. If A, then B.\nP2. Not A.\nC. Therefore, Not B.',
    choices: [
      { id: 'a', text: 'Always valid (Modus Ponens)' },
      { id: 'b', text: 'Always valid (Modus Tollens)' },
      { id: 'c', text: 'Always invalid (Denying the Antecedent)' },
      { id: 'd', text: 'Always invalid (Affirming the Consequent)' },
    ],
    correctChoiceIds: ['c'],
    explanation: 'This is Denying the Antecedent — always invalid form (3). If A then B; not A; therefore not B. This is INVALID because B could be true for reasons other than A.',
    difficulty: 1,
    createdAt: now,
    updatedAt: now,
  },
  {
    id: 'gex-052',
    subjectId,
    topicIds: ['gex-logic-relativism'],
    type: 'mcq_single',
    stem: 'Which of the four common argument forms is this?\n\nP1. If A, then B.\nP2. B.\nC. Therefore, A.',
    choices: [
      { id: 'a', text: 'Always valid (Modus Ponens)' },
      { id: 'b', text: 'Always valid (Modus Tollens)' },
      { id: 'c', text: 'Always invalid (Denying the Antecedent)' },
      { id: 'd', text: 'Always invalid (Affirming the Consequent)' },
    ],
    correctChoiceIds: ['d'],
    explanation: 'This is Affirming the Consequent — always invalid form (4). If A then B; B; therefore A. This is INVALID because B could be true without A being true (e.g., you can be sick without having a cold).',
    difficulty: 1,
    createdAt: now,
    updatedAt: now,
  },

  // --- Applied Logic Questions ---
  {
    id: 'gex-053',
    subjectId,
    topicIds: ['gex-logic-relativism'],
    type: 'mcq_single',
    stem: 'P1. If it is raining, the streets are wet.\nP2. The streets are wet.\nC. Therefore, it is raining.\n\nIs this argument valid or invalid?',
    choices: [
      { id: 'a', text: 'Valid' },
      { id: 'b', text: 'Invalid' },
    ],
    correctChoiceIds: ['b'],
    explanation: 'Invalid. This has the form: If A then B; B; therefore A — which is Affirming the Consequent (always invalid form 4). The streets could be wet for other reasons (sprinklers, flooding). (From 2024 midterm Q4.)',
    difficulty: 2,
    createdAt: now,
    updatedAt: now,
  },
  {
    id: 'gex-054',
    subjectId,
    topicIds: ['gex-logic-relativism'],
    type: 'mcq_single',
    stem: 'P1. If the death penalty deters crime, it is justified.\nP2. The death penalty does not deter crime.\nC. Therefore, the death penalty is not justified.\n\nIs this argument valid or invalid?',
    choices: [
      { id: 'a', text: 'Valid' },
      { id: 'b', text: 'Invalid' },
    ],
    correctChoiceIds: ['b'],
    explanation: 'Invalid. This has the form: If A then B; not A; therefore not B — which is Denying the Antecedent (always invalid form 3). The death penalty could be justified for reasons other than deterring crime.',
    difficulty: 2,
    createdAt: now,
    updatedAt: now,
  },
  {
    id: 'gex-055',
    subjectId,
    topicIds: ['gex-logic-relativism'],
    type: 'mcq_single',
    stem: 'P1. If taking a philosophy course is morally permissible, then taking a philosophy course is morally required.\nP2. Taking a philosophy course is not morally required.\nC. Taking a philosophy course is not morally permissible.\n\nIs this argument valid? Is it sound?',
    choices: [
      { id: 'a', text: 'Valid and sound' },
      { id: 'b', text: 'Valid but unsound' },
      { id: 'c', text: 'Invalid' },
      { id: 'd', text: 'Invalid but with true premises' },
    ],
    correctChoiceIds: ['b'],
    explanation: 'The argument is valid (Modus Tollens: If A then B; not B; therefore not A). But it is unsound because P1 is false — the set of permissible actions is NOT a subset of required actions; it\'s the other way around. (From 2024 midterm Q14.)',
    difficulty: 4,
    createdAt: now,
    updatedAt: now,
  },
  {
    id: 'gex-056',
    subjectId,
    topicIds: ['gex-logic-relativism'],
    type: 'mcq_single',
    stem: 'P1. If Edward Cullen were a human, he would be mortal. (True)\nP2. Edward Cullen is not a human. (True)\nC. Edward Cullen is not mortal. (True)\n\nThis argument has all true premises and a true conclusion. Is it valid?',
    choices: [
      { id: 'a', text: 'Yes — all premises and the conclusion are true, so it must be valid' },
      { id: 'b', text: 'No — it has the invalid form "If A then B; not A; therefore not B" (Denying the Antecedent)' },
    ],
    correctChoiceIds: ['b'],
    explanation: 'Invalid. Despite having all true statements, this argument uses Denying the Antecedent (always invalid form 3). An argument can have true premises and a true conclusion while still being invalid — the conclusion doesn\'t follow logically from the premises.',
    difficulty: 3,
    createdAt: now,
    updatedAt: now,
  },
  {
    id: 'gex-057',
    subjectId,
    topicIds: ['gex-logic-relativism'],
    type: 'mcq_single',
    stem: 'If an argument is shown to be invalid, does that mean its conclusion is false?',
    choices: [
      { id: 'a', text: 'Yes — if the argument is invalid, the conclusion must be false' },
      { id: 'b', text: 'No — it just means this particular argument fails to show the conclusion is true; there might be other good arguments for the same conclusion' },
    ],
    correctChoiceIds: ['b'],
    explanation: 'No. An invalid argument simply fails to establish its conclusion. The conclusion could still be true — it just hasn\'t been demonstrated by THIS argument. There might be other, valid arguments that support the same conclusion.',
    difficulty: 2,
    createdAt: now,
    updatedAt: now,
  },
  {
    id: 'gex-058',
    subjectId,
    topicIds: ['gex-logic-relativism'],
    type: 'mcq_single',
    stem: 'Fill in the blank so that the following argument becomes valid.\n\nP1. Different cultures have different moral codes.\nP2. [___]\nC. Cultural relativism is true.',
    choices: [
      { id: 'a', text: 'If different cultures have different moral codes, cultural relativism is true' },
      { id: 'b', text: 'If cultural relativism is true, different cultures have different moral codes' },
      { id: 'c', text: 'If it is not the case that different cultures have different moral codes, it is not the case that cultural relativism is true' },
      { id: 'd', text: 'Both B and C work' },
    ],
    correctChoiceIds: ['a'],
    explanation: 'Only A works. With A as P2, the argument becomes: P1. A. P2. If A then B. C. B — which is Modus Ponens (valid). B gives: P1. A. P2. If B then A. C. B — Affirming the Consequent (invalid). C gives a similar invalid form. (From 2024 midterm Q1.)',
    difficulty: 3,
    createdAt: now,
    updatedAt: now,
  },

  // --- Cultural Relativism ---
  {
    id: 'gex-059',
    subjectId,
    topicIds: ['gex-logic-relativism'],
    type: 'mcq_single',
    stem: 'What is cultural relativism?',
    choices: [
      { id: 'a', text: 'The view that every culture ought to be tolerant of other cultures' },
      { id: 'b', text: 'The view that the truth of moral judgments is relative to a culture — the moral code of a society determines what is right or wrong within that society, with no universal moral truths' },
      { id: 'c', text: 'The view that all cultures are morally equal' },
      { id: 'd', text: 'The view that moral progress is possible within a culture' },
    ],
    correctChoiceIds: ['b'],
    explanation: 'Cultural relativism holds that moral truth is relative to a culture. The moral code of a society determines what is right/wrong within that society. There is no universal truth in ethics — just various cultural codes, none with special status.',
    difficulty: 1,
    createdAt: now,
    updatedAt: now,
  },
  {
    id: 'gex-060',
    subjectId,
    topicIds: ['gex-logic-relativism'],
    type: 'mcq_single',
    stem: 'Rachels criticizes the common argument for cultural relativism:\n\nP1. Different cultures have different moral codes.\nC. Cultural relativism is true.\n\nWhat is Rachels\' criticism?',
    choices: [
      { id: 'a', text: 'P1 is false — cultures actually agree on morality' },
      { id: 'b', text: 'The argument is invalid — the conclusion (about what IS the case) doesn\'t follow from the premise (about what people BELIEVE); cultures could simply be mistaken' },
      { id: 'c', text: 'The argument is valid but the conclusion is wrong' },
      { id: 'd', text: 'Cultural relativism has already been proven true by other arguments' },
    ],
    correctChoiceIds: ['b'],
    explanation: 'Rachels argues the argument is not sound because it is invalid: the premise is about what people BELIEVE, but the conclusion is about what IS the case. People in different cultures disagreeing doesn\'t mean there\'s no objective truth — just as flat-earthers disagreeing with round-earthers doesn\'t mean there\'s no objective truth about Earth\'s shape.',
    difficulty: 2,
    createdAt: now,
    updatedAt: now,
  },
  {
    id: 'gex-061',
    subjectId,
    topicIds: ['gex-logic-relativism'],
    type: 'mcq_multi',
    stem: 'According to Rachels, if cultural relativism were true, which counterintuitive implications would follow? Select all that apply.',
    choices: [
      { id: 'a', text: 'We could never say that the customs of other societies are morally inferior to our own (e.g., we couldn\'t condemn slavery or anti-Semitism in other cultures)' },
      { id: 'b', text: 'We could decide right and wrong just by consulting the standards of our own society' },
      { id: 'c', text: 'Moral progress would be impossible (we can\'t say current treatment of women is "better" than past treatment)' },
      { id: 'd', text: 'Every culture would be morally required to be tolerant of other cultures' },
    ],
    correctChoiceIds: ['a', 'b', 'c'],
    explanation: 'Rachels lists three implications: (A) can\'t condemn other societies, (B) just consult your own society\'s code, (C) moral progress impossible. D is FALSE — cultural relativism does NOT require tolerance; if a culture\'s code says be intolerant, that\'s right for them.',
    difficulty: 3,
    createdAt: now,
    updatedAt: now,
  },
  {
    id: 'gex-062',
    subjectId,
    topicIds: ['gex-logic-relativism'],
    type: 'mcq_multi',
    stem: 'Which of the following is true according to cultural relativism? Select all correct answers.',
    choices: [
      { id: 'a', text: 'Every culture ought to be tolerant of other cultures' },
      { id: 'b', text: 'It is impossible for a person to perform a morally wrong action within their own culture unless they leave to live elsewhere' },
      { id: 'c', text: 'A member of one culture never has any moral obligations toward a member of another culture' },
      { id: 'd', text: 'None of the above' },
    ],
    correctChoiceIds: ['d'],
    explanation: 'None of the above. A is false (no universal moral truths, so if a culture says be intolerant, that\'s fine). B is false (you can violate your OWN culture\'s moral codes within it). C is false (your culture might require obligations toward outsiders). (From 2024 midterm Q5.)',
    difficulty: 4,
    createdAt: now,
    updatedAt: now,
  },
  {
    id: 'gex-063',
    subjectId,
    topicIds: ['gex-logic-relativism'],
    type: 'mcq_single',
    stem: 'What does Rachels conclude we can learn from cultural relativism, even though he believes it is false?',
    choices: [
      { id: 'a', text: 'All moral judgments are merely cultural preferences with no objective basis' },
      { id: 'b', text: 'Many of our practices are merely cultural products (social conventions), but cultural relativism goes wrong by concluding that ALL practices must be like this' },
      { id: 'c', text: 'We should never judge other cultures at all' },
      { id: 'd', text: 'Science can resolve all moral disagreements' },
    ],
    correctChoiceIds: ['b'],
    explanation: 'Rachels says cultural relativism rightly warns that many of our practices are just social conventions (e.g., women covering breasts, funerary practices). But it goes wrong by concluding that because SOME practices are mere conventions, ALL must be. Some moral truths are universal.',
    difficulty: 2,
    createdAt: now,
    updatedAt: now,
  },
  {
    id: 'gex-064',
    subjectId,
    topicIds: ['gex-logic-relativism'],
    type: 'mcq_single',
    stem: 'How does Rachels explain the Eskimo practice of infanticide?',
    choices: [
      { id: 'a', text: 'The Eskimos had fundamentally different values about human life' },
      { id: 'b', text: 'The Eskimos\' values are not that different from ours; they value infants but live in a harsh environment where difficult choices are forced upon them' },
      { id: 'c', text: 'The Eskimos prove that cultural relativism is true' },
      { id: 'd', text: 'The practice was universally condemned by Eskimo elders' },
    ],
    correctChoiceIds: ['b'],
    explanation: 'Rachels argues that Eskimo families would always protect babies if conditions permitted. Their harsh environment (scarce food, nomadic life, mothers can carry only one baby) forces choices we don\'t have to make. Their underlying values are not that different from ours.',
    difficulty: 2,
    createdAt: now,
    updatedAt: now,
  },

  // ═══════════════════════════════════════════════════════════════════════
  // WEEK 6: RELIGION — THE PROBLEM OF EVIL
  // ═══════════════════════════════════════════════════════════════════════

  {
    id: 'gex-065',
    subjectId,
    topicIds: ['gex-religion'],
    type: 'mcq_single',
    stem: 'The Problem of Evil argues against the existence of what kind of god?',
    choices: [
      { id: 'a', text: 'Any god whatsoever' },
      { id: 'b', text: 'An all-perfect god: omnipotent (all-powerful), omniscient (all-knowing), and omnibenevolent (all-loving/morally perfect)' },
      { id: 'c', text: 'A god that is powerful but not all-knowing' },
      { id: 'd', text: 'A god that created the universe but does not intervene' },
    ],
    correctChoiceIds: ['b'],
    explanation: 'The Problem of Evil specifically targets the existence of an all-perfect god with three features: omnipotent, omniscient, and omnibenevolent. It does not argue against the existence of limited gods.',
    difficulty: 1,
    createdAt: now,
    updatedAt: now,
  },
  {
    id: 'gex-066',
    subjectId,
    topicIds: ['gex-religion'],
    type: 'mcq_single',
    stem: 'The first attempt at the argument from evil is:\n\nP1. If an all-perfect god exists, there are no evils.\nP2. There are evils.\nC. An all-perfect god does not exist.\n\nWhat is the main problem with P1?',
    choices: [
      { id: 'a', text: 'P1 is clearly implausible because God may have good reasons to allow some evils (e.g., a little suffering can lead to greater good, like getting up early for a great fishing day)' },
      { id: 'b', text: 'P1 contradicts P2' },
      { id: 'c', text: 'P1 is too vague to evaluate' },
      { id: 'd', text: 'There is no problem with P1' },
    ],
    correctChoiceIds: ['a'],
    explanation: 'P1 is implausible because an all-perfect god may have good reasons to allow some evils. Just as getting up early (mild suffering) is necessary for a great fishing day, God may allow some suffering as part of a plan for a better world overall.',
    difficulty: 2,
    createdAt: now,
    updatedAt: now,
  },
  {
    id: 'gex-067',
    subjectId,
    topicIds: ['gex-religion'],
    type: 'mcq_single',
    stem: 'The revised argument from evil is:\n\nP1. If an all-perfect god exists, there are no UNJUSTIFIED evils.\nP2. There are unjustified evils.\nC. An all-perfect god does not exist.\n\nWhat does "unjustified evil" mean here?',
    choices: [
      { id: 'a', text: 'Evil that is not punished by law' },
      { id: 'b', text: 'Evil that an all-perfect god has no good reason to allow' },
      { id: 'c', text: 'Evil caused by humans rather than nature' },
      { id: 'd', text: 'Evil that people don\'t believe is wrong' },
    ],
    correctChoiceIds: ['b'],
    explanation: 'An unjustified evil is one that an all-perfect god has no good reason to allow. If allowing the evil is necessary for achieving a more important moral goal (generating a good that outweighs the evil, or preventing a worse evil), it is justified.',
    difficulty: 2,
    createdAt: now,
    updatedAt: now,
  },
  {
    id: 'gex-068',
    subjectId,
    topicIds: ['gex-religion'],
    type: 'mcq_single',
    stem: 'What is the argument form of both versions of the argument from evil (P1: If all-perfect god exists, no [unjustified] evils; P2: There are [unjustified] evils; C: All-perfect god does not exist)?',
    choices: [
      { id: 'a', text: 'Modus Ponens (always valid)' },
      { id: 'b', text: 'Modus Tollens (always valid)' },
      { id: 'c', text: 'Denying the Antecedent (always invalid)' },
      { id: 'd', text: 'Affirming the Consequent (always invalid)' },
    ],
    correctChoiceIds: ['b'],
    explanation: 'The argument has the form: If A then B; not B; therefore not A — which is Modus Tollens (always valid form 2). P1: If god exists (A), no evils (B). P2: There ARE evils (not B). C: God does not exist (not A).',
    difficulty: 2,
    createdAt: now,
    updatedAt: now,
  },

  // --- Theodicies ---
  {
    id: 'gex-069',
    subjectId,
    topicIds: ['gex-religion'],
    type: 'mcq_single',
    stem: 'A theist responds to the problem of evil by saying: "Evil is necessary so we can appreciate the good things in life." What is a counter-objection to this?',
    choices: [
      { id: 'a', text: 'There is no such thing as appreciation' },
      { id: 'b', text: 'Do we need SO MUCH evil to appreciate good? Couldn\'t an all-perfect god make us appreciate good without being exposed to bad? What about evils nobody knows about?' },
      { id: 'c', text: 'This response actually proves God exists' },
      { id: 'd', text: 'Appreciation is only instrumentally valuable' },
    ],
    correctChoiceIds: ['b'],
    explanation: 'The counter-objections are: (1) We don\'t need SO MUCH horrendous evil to appreciate good; (2) Couldn\'t an all-perfect god make us able to appreciate good without exposure to bad? (3) What about bad things that happen without anyone knowing about them?',
    difficulty: 2,
    createdAt: now,
    updatedAt: now,
  },
  {
    id: 'gex-070',
    subjectId,
    topicIds: ['gex-religion'],
    type: 'mcq_multi',
    stem: 'What are the counter-objections to the "evil is necessary for spiritual/moral development" theodicy? Select all that apply.',
    choices: [
      { id: 'a', text: 'Do we really need so much horrendous evil for spiritual development?' },
      { id: 'b', text: 'What about suffering of animals or children who die young?' },
      { id: 'c', text: 'Those who really need spiritual development often do not suffer; those who suffer often end up bitter and morally crippled' },
      { id: 'd', text: 'Couldn\'t an all-perfect god make us already spiritually mature without suffering?' },
    ],
    correctChoiceIds: ['a', 'b', 'c', 'd'],
    explanation: 'All four are counter-objections discussed in the lecture: (A) too much evil for development, (B) animal/child suffering and unnoticed suffering, (C) suffering often doesn\'t correlate with who needs development, (D) god could create us already mature.',
    difficulty: 3,
    createdAt: now,
    updatedAt: now,
  },
  {
    id: 'gex-071',
    subjectId,
    topicIds: ['gex-religion'],
    type: 'mcq_multi',
    stem: 'What are the counter-objections to the "evil is a necessary consequence of free will" theodicy? Select all that apply.',
    choices: [
      { id: 'a', text: 'Why doesn\'t God at least intervene sometimes to prevent the most horrendous outcomes of free will?' },
      { id: 'b', text: 'God and angels presumably have free will and never commit wrongdoing — why couldn\'t God make humans like that too?' },
      { id: 'c', text: 'What about natural evils (earthquakes, cancer, etc.) which are not consequences of human free will?' },
      { id: 'd', text: 'Free will does not actually exist' },
    ],
    correctChoiceIds: ['a', 'b', 'c'],
    explanation: 'The lecture lists counter-objections A, B, and C. The existence of free will itself is questioned but presented as uncertain ("Do we really have free will? — that\'s the topic for another lecture"), not as a definitive counter-objection here.',
    difficulty: 3,
    createdAt: now,
    updatedAt: now,
  },
  {
    id: 'gex-072',
    subjectId,
    topicIds: ['gex-religion'],
    type: 'mcq_single',
    stem: 'Consider this example: Lightning strikes a tree in a remote forest, starting a wildfire. A fawn is badly burned and suffers for days before dying — before any humans existed. Why is this particularly challenging for theists?',
    choices: [
      { id: 'a', text: 'Because it proves that God cannot prevent natural disasters' },
      { id: 'b', text: 'Because none of the common theodicies (appreciation, spiritual development, free will) can easily justify this instance of suffering' },
      { id: 'c', text: 'Because animals don\'t have souls' },
      { id: 'd', text: 'Because it happened before recorded history' },
    ],
    correctChoiceIds: ['b'],
    explanation: 'This case is challenging because: the "appreciation" theodicy fails (no one knew about it), the "spiritual development" theodicy fails (the fawn can\'t develop spiritually), and the "free will" theodicy fails (no human free will involved — it\'s a natural evil). None of the common answers easily justify this suffering.',
    difficulty: 3,
    createdAt: now,
    updatedAt: now,
  },
  {
    id: 'gex-073',
    subjectId,
    topicIds: ['gex-religion'],
    type: 'mcq_single',
    stem: 'A theist responds: "God has good reasons to allow evils, but humans cannot understand those reasons due to our limitations." What are the problems with this response?',
    choices: [
      { id: 'a', text: 'If God is all-loving, why doesn\'t he help us understand? And if we can\'t know what\'s truly good, we lose our moral compass and can\'t predict if our afterlife will be good' },
      { id: 'b', text: 'There are no problems — this is a conclusive response' },
      { id: 'c', text: 'Humans are actually capable of understanding God\'s reasons' },
      { id: 'd', text: 'This response only works for natural evils, not moral evils' },
    ],
    correctChoiceIds: ['a'],
    explanation: 'Problems: (1) If God is all-loving, why not help us bear suffering by letting us understand? (2) If we can\'t know what\'s truly good, we lose our moral compass. (3) We can\'t predict how God might behave — no reason to think our afterlife will be good (in our sense).',
    difficulty: 3,
    createdAt: now,
    updatedAt: now,
  },
  {
    id: 'gex-074',
    subjectId,
    topicIds: ['gex-religion'],
    type: 'mcq_single',
    stem: 'In the context of the problem of evil, "evil" refers to:',
    choices: [
      { id: 'a', text: 'Only immoral actions committed by humans' },
      { id: 'b', text: 'Suffering and misfortune (not specifically immorality)' },
      { id: 'c', text: 'Only natural disasters' },
      { id: 'd', text: 'Actions committed by supernatural beings' },
    ],
    correctChoiceIds: ['b'],
    explanation: 'In the problem of evil, "evil" means suffering and misfortune — not specifically immorality. This includes both moral evils (caused by humans) and natural evils (earthquakes, diseases, etc.).',
    difficulty: 1,
    createdAt: now,
    updatedAt: now,
  },
  {
    id: 'gex-075',
    subjectId,
    topicIds: ['gex-religion'],
    type: 'mcq_single',
    stem: 'Which of the following is a "natural evil" as opposed to a "moral evil"?',
    choices: [
      { id: 'a', text: 'Murder' },
      { id: 'b', text: 'Theft' },
      { id: 'c', text: 'An earthquake that destroys a village' },
      { id: 'd', text: 'Lying to a friend' },
    ],
    correctChoiceIds: ['c'],
    explanation: 'Natural evils are suffering not caused by human choice — earthquakes, floods, tsunamis, cancer, etc. Moral evils (murder, theft, lying) are caused by human free will. The free will theodicy cannot address natural evils.',
    difficulty: 1,
    createdAt: now,
    updatedAt: now,
  },
];

export const gex1015Seed: SeedBundle = {
  subjects: [
    { id: subjectId, name: 'GEX1015 Life, the Universe, and Everything' },
  ],
  topics,
  questions,
};
