import type { Question, Subject, Topic } from '../src/models';

export interface SeedBundle {
  subjects: Subject[];
  topics: Topic[];
  questions: Question[];
}

const now = new Date().toISOString();

const subjectId = 'security-plus';

const topics: Topic[] = [
  { id: 'threats-attacks', subjectId, name: 'Threats, Attacks & Vulnerabilities' },
  { id: 'architecture-design', subjectId, name: 'Architecture & Design' },
  { id: 'implementation', subjectId, name: 'Implementation' },
  { id: 'operations', subjectId, name: 'Operations & Incident Response' },
  { id: 'governance', subjectId, name: 'Governance, Risk & Compliance' },
];

const questions: Question[] = [
  {
    id: 'sp-mcq-001',
    subjectId,
    topicIds: ['threats-attacks'],
    type: 'mcq_single',
    stem: 'Which attack relies on manipulating ARP tables to intercept LAN traffic?',
    choices: [
      { id: 'a', text: 'DNS poisoning' },
      { id: 'b', text: 'MAC flooding' },
      { id: 'c', text: 'ARP spoofing' },
      { id: 'd', text: 'Port scanning' },
    ],
    correctChoiceIds: ['c'],
    explanation: 'ARP spoofing allows an attacker to redirect traffic by falsifying MAC-to-IP mappings.',
    difficulty: 3,
    difficultyLabel: 'medium',
    createdAt: now,
    updatedAt: now,
  },
  {
    id: 'sp-mcq-002',
    subjectId,
    topicIds: ['threats-attacks'],
    type: 'mcq_single',
    stem: 'A red team is using a phishing toolkit with pretexting. Which social engineering principle is being exploited?',
    choices: [
      { id: 'a', text: 'Scarcity' },
      { id: 'b', text: 'Authority' },
      { id: 'c', text: 'Urgency' },
      { id: 'd', text: 'Reciprocity' },
    ],
    correctChoiceIds: ['b'],
    explanation: 'Pretexting often leverages authority to increase trust in the attacker.',
    difficulty: 2,
    difficultyLabel: 'easy',
    createdAt: now,
    updatedAt: now,
  },
  {
    id: 'sp-mcq-003',
    subjectId,
    topicIds: ['architecture-design'],
    type: 'mcq_single',
    stem: 'Which security control best enforces separation of duties in cloud deployments?',
    choices: [
      { id: 'a', text: 'RBAC with least privilege roles' },
      { id: 'b', text: 'Multifactor authentication' },
      { id: 'c', text: 'Segmentation gateways' },
      { id: 'd', text: 'Network security groups' },
    ],
    correctChoiceIds: ['a'],
    explanation: 'Role-based access control with least privilege ensures no single user has full control.',
    difficulty: 3,
    difficultyLabel: 'medium',
    createdAt: now,
    updatedAt: now,
  },
  {
    id: 'sp-mcq-004',
    subjectId,
    topicIds: ['implementation'],
    type: 'mcq_single',
    stem: 'Which protocol secures LDAP communications?',
    choices: [
      { id: 'a', text: 'LDAPS' },
      { id: 'b', text: 'SFTP' },
      { id: 'c', text: 'Kerberos' },
      { id: 'd', text: 'CHAP' },
    ],
    correctChoiceIds: ['a'],
    explanation: 'LDAPS wraps LDAP in TLS for encryption and integrity.',
    difficulty: 2,
    difficultyLabel: 'easy',
    createdAt: now,
    updatedAt: now,
  },
  {
    id: 'sp-mcq-005',
    subjectId,
    topicIds: ['operations'],
    type: 'mcq_single',
    stem: 'During incident response, which phase focuses on lessons learned and process improvement?',
    choices: [
      { id: 'a', text: 'Preparation' },
      { id: 'b', text: 'Containment' },
      { id: 'c', text: 'Eradication' },
      { id: 'd', text: 'Post-incident activity' },
    ],
    correctChoiceIds: ['d'],
    explanation: 'Post-incident activity includes root cause analysis and documentation updates.',
    difficulty: 2,
    difficultyLabel: 'easy',
    createdAt: now,
    updatedAt: now,
  },
  {
    id: 'sp-mcq-006',
    subjectId,
    topicIds: ['governance'],
    type: 'mcq_single',
    stem: 'Which framework is most associated with risk-based cybersecurity controls in the US?',
    choices: [
      { id: 'a', text: 'ISO/IEC 27001' },
      { id: 'b', text: 'NIST CSF' },
      { id: 'c', text: 'COBIT' },
      { id: 'd', text: 'ITIL' },
    ],
    correctChoiceIds: ['b'],
    explanation: 'The NIST Cybersecurity Framework is widely adopted for risk-based controls.',
    difficulty: 3,
    difficultyLabel: 'medium',
    createdAt: now,
    updatedAt: now,
  },
  {
    id: 'sp-mcq-007',
    subjectId,
    topicIds: ['implementation'],
    type: 'mcq_single',
    stem: 'What does certificate pinning defend against?',
    choices: [
      { id: 'a', text: 'Buffer overflow attacks' },
      { id: 'b', text: 'Man-in-the-middle attacks with rogue certs' },
      { id: 'c', text: 'SQL injection' },
      { id: 'd', text: 'Privilege escalation' },
    ],
    correctChoiceIds: ['b'],
    explanation: 'Pinning enforces that clients trust only specific certificates to prevent MITM.',
    difficulty: 3,
    difficultyLabel: 'medium',
    createdAt: now,
    updatedAt: now,
  },
  {
    id: 'sp-mcq-008',
    subjectId,
    topicIds: ['architecture-design'],
    type: 'mcq_single',
    stem: 'Which design principle minimises blast radius by isolating workloads?',
    choices: [
      { id: 'a', text: 'Defense in depth' },
      { id: 'b', text: 'Segmentation' },
      { id: 'c', text: 'Obfuscation' },
      { id: 'd', text: 'Availability' },
    ],
    correctChoiceIds: ['b'],
    explanation: 'Segmentation limits impact by separating resources into security zones.',
    difficulty: 2,
    difficultyLabel: 'easy',
    createdAt: now,
    updatedAt: now,
  },
  {
    id: 'sp-mcq-009',
    subjectId,
    topicIds: ['operations'],
    type: 'mcq_multi',
    stem: 'Select the best logging targets for detecting credential stuffing.',
    choices: [
      { id: 'a', text: 'Authentication success/failure logs' },
      { id: 'b', text: 'Backup job reports' },
      { id: 'c', text: 'Web server access logs' },
      { id: 'd', text: 'Database performance dashboards' },
    ],
    correctChoiceIds: ['a', 'c'],
    explanation: 'Credential stuffing shows abnormal auth activity and high-volume HTTP requests.',
    difficulty: 3,
    difficultyLabel: 'medium',
    createdAt: now,
    updatedAt: now,
  },
  {
    id: 'sp-mcq-010',
    subjectId,
    topicIds: ['governance'],
    type: 'mcq_single',
    stem: 'A company wants to ensure vendors follow minimum security practices. Which document formalises this?',
    choices: [
      { id: 'a', text: 'SOW' },
      { id: 'b', text: 'SLA' },
      { id: 'c', text: 'MOU' },
      { id: 'd', text: 'Security addendum' },
    ],
    correctChoiceIds: ['d'],
    explanation: 'A security addendum (or security requirement clause) enforces controls in vendor contracts.',
    difficulty: 3,
    difficultyLabel: 'medium',
    createdAt: now,
    updatedAt: now,
  },
  {
    id: 'sp-pbq-001',
    subjectId,
    topicIds: ['operations'],
    type: 'pbq_order',
    stem: 'Order the incident response phases from first to last.',
    pbqSpec: {
      instructions: 'Drag cards into the correct sequence.',
      configuration: {
        ordering: ['Preparation', 'Identification', 'Containment', 'Eradication', 'Recovery', 'Lessons Learned'],
      },
    },
    explanation: 'Incident response follows a repeatable life cycle to improve readiness and recovery.',
    createdAt: now,
    updatedAt: now,
  },
  {
    id: 'sp-pbq-002',
    subjectId,
    topicIds: ['implementation'],
    type: 'pbq_match',
    stem: 'Match the secure protocol to the legacy protocol it replaces.',
    pbqSpec: {
      instructions: 'Pair each secure protocol with its legacy counterpart.',
      configuration: {
        pairs: [
          { secure: 'SFTP', legacy: 'FTP' },
          { secure: 'SNMPv3', legacy: 'SNMPv1' },
          { secure: 'HTTPS', legacy: 'HTTP' },
        ],
      },
    },
    explanation: 'Secure variants add encryption, integrity, and authentication improvements.',
    createdAt: now,
    updatedAt: now,
  },
];

export const securityPlusSeed: SeedBundle = {
  subjects: [{ id: subjectId, name: 'CompTIA Security+' }],
  topics,
  questions,
};
